server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sfsb
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth.ra58.ru/realms/sfsb-realm/protocol/openid-connect/certs
  main:
    allow-circular-references: true
  banner:
    location: classpath:banner.txt
springAsyncConfig:
  corePoolSize: 4
  maxPoolSize: 10
  queueCapacity: 50
  threadNamePrefix: 'AsyncTaskThread::'
  waitForTasksToCompleteOnShutdown: true
logging:
  level:
    root: OFF
    org:
      springframework:
        security: DEBUG
    org.hibernate: INFO
    ru.erp.sfsb: DEBUG
  file:
    name: logs/log.log
    max-size: 1mb
    max-history: 7
webclient:
  file-service:
    file-url: http://fs.ra58.ru:9000/api/file
    connect-timeout: 5000
    read-timeout: 5000
    external-url: http://fs.ra58.ru:9000/api/file
keycloak:
  auth-server-url: http://auth.ra58.ru
  realm: sfsb-realm
  resource: sfsb-user-manage-client
  ssl-required: external
  credentials:
    secret: aP9J72MFDrdnqNu9L1KCqrRZh8jDIeKf
  use-resource-role-mappings: true
cors:
  url: http://ra58.ru
  ip: http://5.35.82.6