server:
  port: 9001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sfsb
    driver-class-name: org.postgresql.Driver
#    username: sfsb
#    password: gFNQkM
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true
  banner:
    location: classpath:banner.txt
springAsyncConfig:
  corePoolSize: 4
  maxPoolSize: 10
  queueCapacity: 50
  threadNamePrefix: 'AsyncTaskThread::'
  waitForTasksToCompleteOnShutdown: true
logging:
  level:
    root: OFF
    org.springframework: INFO
    org.hibernate: INFO
    ru.erp.sfsb: DEBUG
  file:
    name: logs/log.log
    max-size: 1mb
    max-history: 7

#keycloak:
#  auth-server-url: http://localhost:8282/auth
#  realm: "sfsb"
#  resource: "sfsb"
#  bearer-only: true
#  security-constraints:
#    - authRoles:
#        - uma_authorization
#      securityCollections:
#        - patterns:
#            - /api/*