server:
  port: 9000
spring:
  datasource:
    url: ${DB-URL}
    driver-class-name: ${DB-DRIVER-CLASS-NAME}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK-SET-URI}
  main:
    allow-circular-references: true
  banner:
    location: classpath:banner.txt
springAsyncConfig:
  corePoolSize: 4
  maxPoolSize: 10
  queueCapacity: 50
  threadNamePrefix: 'AsyncTaskThread::'
  waitForTasksToCompleteOnShutdown: true
logging:
  level:
    root: OFF
    org.springframework: INFO
    org.hibernate: INFO
    ru.erp.sfsb: DEBUG
  file:
    name: logs/log.log
    max-size: 1mb
    max-history: 7
webclient:
  file-service:
    file-url: ${FILE-URL}
    connect-timeout: 5000
    read-timeout: 5000
  cp-store:
    url: ${CP-STORE-URL}
keycloak:
  auth-server-url: ${KC_AUTH_SERVER_URL}
  realm: ${KC_REALM}
  resource: ${KC_AUTH_RESOURCE}
  ssl-required: external
  credentials:
    secret: ${KC_AUTH_SECRET}
  use-resource-role-mappings: true
cors:
  url: ${CORS_URL}
  ip: ${CORS_IP}
  cp: ${CORS_CP}