version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/data/db
    environment:
      POSTGRES_USER: sfsb
      POSTGRES_PASSWORD: gFNQkM
      POSTGRES_DB: sfsb
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  adminer:
    image: adminer
    restart: always
    ports:
      - "9002:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  sfsb:
    image: shaman58/sfsb:0.0.2
    restart: always
    ports:
      - "9001:9001"
  sfsb-front:
    image: shaman58/sfsb-front:0.0.2
    restart: always
    ports:
      - "9003:3000"
      - "80:80"
  file-server:
    build: ./nginx
    ports:
      - "9004:80"
    volumes:
      - files:/data/files
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    labels:
      - "com.centurylinklabs.watchtower.enable=false"


volumes:
  files:
  db-data:
