version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/data/db
    environment:
      POSTGRES_USER: sfsb
      POSTGRES_PASSWORD: gFNQkM
      POSTGRES_DB: sfsb
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  adminer:
    image: adminer
    restart: always
    ports:
      - "9002:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  sfsb:
    image: shaman58/sfsb:0.0.2
    restart: always
    ports:
      - "9001:9001"
  sfsb-front:
    image: shaman58/sfsb-front:0.0.2
    restart: always
    ports:
      - "9003:3000"
      - "80:80"
  file-server:
    build: ./nginx
    ports:
      - "9004:80"
    volumes:
      - files:/data/files
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  keycloak-postgres:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    restart: on-failure
    environment:
      POSTGRES_USER: sfsb
      POSTGRES_PASSWORD: gFNQkM
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - ${KC_POSTGRES_PORT_MAPPING:-5435}:5432
    deploy:
      resources:
        limits:
          memory: 256M
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/postgres
      KC_DB_USERNAME: sfsb
      KC_DB_PASSWORD: gFNQkM
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: sfsb
      KEYCLOAK_ADMIN_PASSWORD: gFNQkM
    ports:
      - "8282:8080"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master" ]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
    labels:
      - "com.centurylinklabs.watchtower.enable=false"


volumes:
  files:
  db-data:
