package ru.erp.sfsb;

public enum LogTag {
    TOKEN_SUPPLIER,
    REPORT_SERVICE,
    CP_STORE_UTIL,
    ADDITIONAL_TOOL_SERVICE,
    COMPANY_SERVICE,
    CUSTOMER_SERVICE,
    CUTTER_TOOL_SERVICE,
    FILE_SERVICE,
    ITEM_SERVICE,
    MATERIAL_DENSITY_SERVICE,
    MATERIAL_SERVICE,
    MEASURE_TOOL_SERVICE,
    OPERATION_SERVICE,
    ORDER_SERVICE,
    SETUP_SERVICE,
    SPECIAL_TOOL_SERVICE,
    TECHNOLOGY_SERVICE,
    TOOLING_SERVICE,
    USER_SERVICE,
    WORKPIECE_SERVICE,
    FILE_SERVER_UTIL,
    DOCX_REPORT_UTIL,
    XLSX_REPORT_UTIL
}