version: '3.9'

services:
  sfsb-front:
    image: voskanvl/sfsb-front:0.2.1
    restart: always
    ports:
      - "80:80"
  sfsb-front-test:
    image: voskanvl/sfsb-front:0.2.2
    restart: always
    ports:
      - "3000:80"
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    labels:
      - "com.centurylinklabs.watchtower.enable=false"