name: sfsb test deploy

on:
  push:
    branches: [ "release" ]
  merge:
    branches: [ "release" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy release
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/sfsb_test/sfsb
            git pull
            ./mvnw package
            cd /home/sfsb_test/sfsb/src/test
            docker-compose build    
            docker-compose up -d