name: sfsb prod deploy



jobs:
  on:
    pull-request:
      branches: [ "deploy/master" ]

  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy release
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/sfsb-github-actions/sfsb
            git pull
            ./mvnw package            
            docker-compose build    
            docker-compose up -d