version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-users:/data/db
    environment:
      POSTGRES_USER: sfsb
      POSTGRES_PASSWORD: gFNQkM
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -d postgres -U sfsb
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.2
    command:
      - start
      - --db postgres
      - --hostname-strict-https false
      - --hostname-strict false
      - --proxy edge
      - --http-enabled true
      - --import-realm
      - --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://db:5432/postgres
      KC_DB_USERNAME: sfsb
      KC_DB_PASSWORD: gFNQkM
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: sfsb
      KEYCLOAK_ADMIN_PASSWORD: gFNQkM
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/localhostcert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/localhostkey.pem
    ports:
      - "80:8080"
      - "443:8443"
    healthcheck:
      test: "exit 0"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./certs:/opt/keycloak/certs
volumes:
  db-users: